import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/Day2Components/ThemeProvider";
import { LanguageProvider } from "@/Day2Components/LanguageProvider";
import { ParentProvider } from "@/Day3Components/ParentProvider";
import { LightLoginProvider } from "@/Day3Components/LIghtLoginProvider";
import { ValidationProvider } from "@/Day3Components/ValidationContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ThemeProvider>
          <LanguageProvider>
            <ParentProvider>
              <LightLoginProvider>
                <ValidationProvider>
                  
              {children}
                </ValidationProvider>
              </LightLoginProvider>
            </ParentProvider>
            
          </LanguageProvider>
        </ThemeProvider>
        
      </body>
    </html>
  );
}
